version: "3.9"

services:
  app:
    build: .
    container_name: app
    restart: always
    environment:
      - JWT_SECRET=RAHASIA
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /Users/udibagas/db:/var/lib/postgresql/data
