# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  JWT_SECRET: INIKODERAHASIA
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: db_finaleproject
  DB_USER: postgres
  DB_PASS: mysecretpassword

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: mysecretpassword

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install package
        run: npm install
      - name: Create database
        run: npx sequelize db:create --env test
      - name: Migration
        run: npx sequelize db:migrate --env test
      - name: Seed Movies Data
        run: npx sequelize db:seed --env test --seed 20240823143631-seeding_movie_datas.js
      - name: Testing
        run: npm test
